spring:
  application:
    name: "localstack"
cloud:
  aws:
    credentials:
      name: "MySecrets"
    region:
      static: us-east-1
    endpoint:
      url: "http://localhost:4566"
    services:
      sqs:
        queue-url: "http://localhost:4566/000000000000/"
      sns:
        topic-url: "arn:aws:sns:us-east-1:000000000000:"